### ISSUE TITLE
How to exclude a field from the request if the user does not have enough rights to access this field or if the condition is not met?

### ISSUE THREAD

**Issue by zabavnikov** [gregorip02/restql#11]

**Comment by gregorip02** [comment]
Hi @zabavnikov 

Trying to solve this, I developed a new function available in the trait `Restql\Traits\RestqlAttributes` with which you can establish a list of "selectable" attributes.

Update to version `2.2` using `composer update gregorip02/restql`.

Hope this works, let me know and we will close this issue.

**Comment by gregorip02** [comment]
https://github.com/gregorip02/restql/releases/tag/v2.2.0

**Comment by gregorip02** [comment]
Closing by inactivity...
